# Training arguments
num_epochs: 10
num_hidden: 64
num_layers: 2
fan_out: "55,65"
batch_size: 2048
batch_size_eval: 1000000
eval_every: 1
lr: 0.0005

# distributed
log_every: 20

# local
num_dl_workers: 4

# Whether to use heterogeneous graph for training and predicting
heterogeneous: true

# Whether to use an inductive model or transductive model
inductive: true

# If use inductive mode, the feature to use as node input feature
node_feature: feat
