# Cloud-provider specific configuration.
provider:
    type: kubernetes

    cloud_provider:
        type: gcp

# The instance configuration for a standard instance type
available_node_types:
    head.default:
        node_config:
            resources:
                cpu: 3
                # 16GB - 3GB
                memory: 13Gi
            dataDisks:
              - name: data-disk-1
                storageClass: "standard-rwo"
                diskSize: 100Gi
    worker.default:
        node_config:
            resources:
                cpu: 3
                # 16GB - 3GB
                memory: 13Gi
            dataDisks:
              - name: data-disk-1
                storageClass: "premium-rwo"
                diskSize: 200Gi
