from: kubernetes/aks/small

# A unique identifier for the head node and workers of this cluster.
cluster_name: example-cluster

# Workspace name
workspace_name: example-workspace

# Kubernetes provider specific configurations
provider:
    type: kubernetes

    # Cloud-provider specific configuration.
    cloud_provider:
        type: azure
        location: eastus
        subscription_id: your-subscription-id
        aks_resource_group: your-aks-resource-group
        aks_cluster_name: your-aks-cluster
        use_managed_cloud_storage: True

available_node_types:
    worker.default:
        # The minimum number of worker nodes to launch.
        min_workers: 3
