# Cloud-provider specific configuration.
provider:
    type: aliyun

# The instance configuration for a standard instance type
available_node_types:
    head.default:
        node_config:
            InstanceType: ecs.g6.4xlarge
            SystemDisk:
                DiskName: os-disk
                Category: cloud_ssd
                Size: 256
    worker.default:
        node_config:
            SystemDisk:
                DiskName: os-disk
                Category: cloud_ssd
                Size: 256
            DataDisk:
              - DiskName: data-disk-1
                Category: cloud_ssd
                Size: 500
