target_col: is_fraud?
ignore_cols: ['merchant_name','user', 'card', 'split']
# data_split is for training only
data_split:
  train: df[df["year"]<2018]
  valid: df[df["year"]==2018]
  test: df[df["year"]>2018]
