# Custom commands that will be run on the head node after common setup.
head_setup_commands:
    - cloudtik runtime install coredns --head
    - cloudtik runtime configure coredns --head

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands:
    - cloudtik runtime install coredns
    - cloudtik runtime configure coredns

# Command to start on the head node. You don't need to change this.
head_start_commands:
    - cloudtik runtime services coredns start --head

# Command to start on worker nodes. You don't need to change this.
worker_start_commands:
    - cloudtik runtime services coredns start

# Command to start on the head node. You don't need to change this.
head_stop_commands:
    - cloudtik runtime services coredns stop --head

# Command to start on worker nodes. You don't need to change this.
worker_stop_commands:
    - cloudtik runtime services coredns stop
