model_name_or_path: emilyalsentzer/Bio_ClinicalBERT
tokenizer_name: emilyalsentzer/Bio_ClinicalBERT
smoke_test: false
max_test_samples: null
max_train_samples: null
max_seq_len: 64
overwrite_cache: true
preprocessing_num_workers: 4
