# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: MIT

node_types:
  - card
  - merchant
node_columns:
  card_id: card
  merchant_id: merchant
#list of column names you want to include in graph as node features
#if column names have special characters or spaces wrap in double quotes
node_features:
  card_id: [card_id]
  merchant_id: [merchant_id]
#provide the column names in your CSV file that contain the entity (node) IDs
#Edge type name in string triplet: [source node type, relation type, destination node type].
edge_types:
  - [card_id, pay, merchant_id]
  - [merchant_id, charge, card_id]
reverse_edges:
  pay: charge
  charge: pay
#list of column names you want to include in graph as edge features
#if column names have special characters or spaces wrap in double quotes
edge_features:
  pay: [year,month,day,time,amount,merchant_name,merchant_city,merchant_state,zip,mcc,"use_chip_Chip Transaction","use_chip_Online Transaction","use_chip_Swipe Transaction","Bad CVV","Bad Card Number","Bad Expiration","Bad PIN","Bad Zipcode","Insufficient Balance","Technical Glitch"]
  charge: [year,month,day,time,amount,merchant_name,merchant_city,merchant_state,zip,mcc,"use_chip_Chip Transaction","use_chip_Online Transaction","use_chip_Swipe Transaction","Bad CVV","Bad Card Number","Bad Expiration","Bad PIN","Bad Zipcode","Insufficient Balance","Technical Glitch"]
#column name in CSV that containers the label
edge_label: "is_fraud?"
#column name in CSV that contains train/test/val splits.
#It is required (0,1,2) are used respectively and all three splits need to be present
edge_split: split
