# Custom commands that will be run on the head node after common setup.
head_setup_commands:
    - cloudtik-flink install --head
    - cloudtik-flink configure --head --node_ip_address=$CLOUDTIK_NODE_IP

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands:
    - cloudtik-flink install
    - cloudtik-flink configure --node_ip_address=$CLOUDTIK_NODE_IP --head_address=$CLOUDTIK_HEAD_IP

# Command to start on the head node. You don't need to change this.
head_start_commands:
    - cloudtik-flink stop-head
    - cloudtik-flink start-head

# Command to start on worker nodes. You don't need to change this.
worker_start_commands:
    - cloudtik-flink stop-worker
    - cloudtik-flink start-worker

# Command to start on the head node. You don't need to change this.
head_stop_commands:
    - cloudtik-flink stop-head

# Command to start on worker nodes. You don't need to change this.
worker_stop_commands:
    - cloudtik-flink stop-worker
