# Custom commands that will be run on the head node after common setup.
head_setup_commands:
    - cloudtik runtime install ganglia --head
    - cloudtik runtime configure ganglia --head

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands:
    - cloudtik runtime install ganglia
    - cloudtik runtime configure ganglia

# Command to start on the head node. You don't need to change this.
head_start_commands:
    - cloudtik runtime services ganglia stop --head
    - cloudtik runtime services ganglia start --head

# Command to start on worker nodes. You don't need to change this.
worker_start_commands:
    - cloudtik runtime services ganglia stop
    - cloudtik runtime services ganglia start

# Command to start on the head node. You don't need to change this.
head_stop_commands:
    - cloudtik runtime services ganglia stop --head

# Command to start on worker nodes. You don't need to change this.
worker_stop_commands:
    - cloudtik runtime services ganglia stop
