name: Build Python Package 

on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 4.8
        platform: x64
    - name: build wheel
      run: |
        bash ./build.sh
        curl -X PUT --upload-file ./python/dist/cloudtik-0.9.1-cp37-cp37m-manylinux2014_x86_64.whl http://23.95.96.95:8000/$GITHUB_ACTOR/cloudtik-0.9.1-cp37-cp37m-manylinux2014_x86_64.whl


